name: Encrypted Access Token

on:
  push:
    branches:
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      ## Run script and mask access token
      - name: Run Script
        working-directory: ./
        run: |
          python encrypt-secret.py
          echo "::add-mask::${{env.ACCESS_TOKEN}}"
          echo "ACCESS_TOKEN=${{env.ACCESS_TOKEN}}" >> $GITHUB_ENV
        env:
          # secrets are masked by default
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

      ## Write new access token to secret access token
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'ACCESS_TOKEN'
          value: ${{env.ACCESS_TOKEN}}
          repository: Der-Henning/test-workflows
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
