name: Encrypted Access Token

on:
  push:
    branches:
      - dev

jobs:
  example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install -r requirements.txt

      ## Run script and mask access token
      - name: Run Script
        working-directory: ./
        run: |
          python encrypt-secret.py
          echo "::add-mask::${{env.ACCESS_TOKEN}}"
          echo "ACCESS_TOKEN=${{env.ACCESS_TOKEN}}" >> $GITHUB_ENV
        env:
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}

      ## Write new access token to secret access token
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'ACCESS_TOKEN'
          value: ${{env.ACCESS_TOKEN}}
          repository: Der-Henning/test-workflows
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
